title: Learning Energy Conserving Dynamics Efficiently with Hamiltonian Gaussian Processes
description: In Transactions on Machine Learning Research (TMLR), March 2023
author: Magnus Ross and Markus Heinonen
theme: jekyll-theme-cayman
